### PR TITLE
Fix for issue  #18520

### PR DESCRIPTION
**Pull request by elburgl69**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix for issue #18520 <br> Will make sure HTML used in ps_customtext is processed by the object presenter in order to enable the filterHtmlContent hook.
| Type?         | bug fix 
| BC breaks?    |  No
| Deprecations? |  No
| Fixed ticket? | Fixes PrestaShop/Prestashop#{18520}.
| How to test?  | Install a module that uses the filterHtmlHook (example module included in issue) and include the trigger code in ps_customtext HTML.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_customtext/50)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please squash your commits, it's unreadable:
image

**Comment by elburgl69** [comment]
Squashed my commits

**Comment by atomiix** [comment]
@elburgl69 you shouldn't have merge commit in your branch. Can you please rebase your PR?

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
It will be easier for you if you redo your pull request.
Please don't forget to add a proper title: "Fix for issue" doesn't mean anything in the git history

**Comment by elburgl69** [comment]
Will do so in Januari. Currently very busy bring a webshop live for a clothingshop that is currently  closed due to Lock down measurenments.

**Comment by elburgl69** [comment]
Creating a new one

**Pull request closed without merging**
