### PR TITLE
Renders form twice on error

### PR DESCRIPTION
**Pull request by bhavikvaghani**
Renders form twice on error.

## How to test ?

https://www.awesomescreenshot.com/video/886584?key=bae6f983e9b8d537fee9359b333935ee

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_customtext/35)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @bhavikvaghani,

Could you give us a scenario case in order to test ?

Thank you!

**Comment by bhavikvaghani** [comment]
Hello @sarahdib ,

 You can check this video.
https://www.awesomescreenshot.com/video/886584

Thank you.

**Comment by Progi1984** [comment]
@bhavikvaghani Your video is not accessible.

**Comment by bhavikvaghani** [comment]
Please check this URL
https://www.awesomescreenshot.com/video/886584?key=bae6f983e9b8d537fee9359b333935ee

**Comment by Progi1984** [comment]
Thanks @bhavikvaghani & @sarahdib

**Pull request merged**
